### ISSUE TITLE
Should ABNF support numeric offsets in brackets?

### ISSUE THREAD

**Issue by justingrant** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#12]
The current ABNF for the time zone extension does not support offset time zones, e.g. `[+08:45]`. These zones are supported in java.time.ZonedDateTime, which is the prior art driving the bracketed time zone extension format. Therefore, I'm assuming that it makes sense for the standard to also allow offsets in brackets too.  

Current ABNF:

https://github.com/ietf-wg-sedate/draft-ietf-sedate-datetime-extended/blob/0e54f23f0d56a647962084ccd3c858931c09233f/draft-ietf-sedate-datetime-extended.md#L346-L351

Suggested ABNF for`time-zone`, where `time-numoffset` is imported from RFC 3339: 

```
time-zone         = "[" time-zone-name / time-numoffset "]"
```

Example of Java usage:

```java
public class MyClass {
    public static void main(String args[]) {
      java.time.ZonedDateTime zdt = java.time.ZonedDateTime.parse("2021-12-09T00:00-08:00[-08:00]");
      System.out.println(zdt.toString());
    }
}
```

**Comment by cabo** [comment]
Please excuse my ignorance: What is the meaning of `-08:00[-08:00]`?  We'd need some text explaining the semantics.

**Comment by justingrant** [comment]
> What is the meaning of `-08:00[-08:00]`

This format asserts that derived timestamps (e.g. add one day) should also use the `-08:00` offset.  It's mostly for backwards compatibility with Java.time. It's not recommended for normal use. 

Heres the explanatory text I added to in #15: 

> Offset Time Zone:
> : A time zone defined by a specific UTC offset, e.g. `+08:45` and
>   serialized using the same numieric UTC offset format used in an
>   RFC 3339 timestamp. Although serialization with offset time zones is
>   supported in this document for backwards compatibility with
>   java.time.ZonedDateTime {{JAVAZDT}}, use of offset time zones is
>   strongly discouraged. In particular, programs MUST NOT copy the UTC
>   offset from a timestamp into an offset time zone in order to satisfy
>   another program which requires a time zone annotation in its input.
>   Doing this will improperly assert that the UTC offset of timestamps
>   in that location will never change, which can result in incorrect
>   calculations in programs that add, subtract, or otherwise derive new
>   timestamps from the one provided. For example,
>   `2020-01-01T00:00+01:00[Europe/Paris]` will let programs add six
>   months to the timestamp while adjusting for Daylight Saving Time.
>   But the same calculation applied to `2020-01-01T00:00+01:00[+01:00]`
>   will produce an incorrect result that will be off by one hour.
>

**Comment by justingrant** [comment]
I assume that conflicts between the timestamp offset and a bracketed offset (e.g. `2020-01-01T00:00+01:00[+02:00]`) should be handled the same as other conflicts, per discussion in https://github.com/ietf-wg-sedate/draft-ietf-sedate-datetime-extended/issues/17.
