### ISSUE TITLE
How to handle conflicts between timestamp offset vs. bracketed timezone?

### ISSUE THREAD

**Issue by justingrant** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#17]
It's possible for a timestamp's offset to conflict with the timezone extension. Usually this is caused by a programmer bug where the wrong offset or the wrong timezone was put in the string. 

However, in rare cases changes to TZDB rules can cause a conflict. Assume `2020-01-15T12:00-02:00[America/Sao_Paulo]` was stored by a program running in 2018 using TZDB rules in effect that time. But after Brazil's time zone rules were changed in April 2019, the correct offset for that point in time is now `-03:00`.

How should the SEDATE standard deal with conflicts like this?

**_UPDATE 2022-03-21:_** 

Our (Temporal team's) understanding is that the WG wants the new standard to be a strict superset of RFC 3339, which implies that the timestamp should be considered a higher priority than the bracketed time zone extension. Using the Brazil example above, a timezone-aware implementation using the current TZDB should interpret `2020-01-15T12:00-02:00[America/Sao_Paulo]` (now the wrong offset) as the same timestamp but a different local time: `2020-01-15T11:00-03:00[America/Sao_Paulo]`.

If this understanding is correct, then here's strawman text for discussion: 

> If a time zone extension is present, then:
> - If the offset is `Z` or `-00:00`, then a timezone-aware implementation SHOULD use the time zone extension to determine the local date, time-of-day, and offset.
> - Otherwise: 
>   - The date, time-of-day, and offset in the string SHOULD express the local date, time-of-day, and offset in that time zone according to the time zone rules that were active when the timestamp was recorded.
>   - If the date, time-of-day, and offset are now not valid for that time zone (e.g. because TZDB rules changed after the timestamp was recorded) then a timezone-aware implementation SHOULD calculate the local date, time-of-day, and offset using its current time zone rules.

Our assumption is that a later standard (maybe the same one that will standardize floating times?) may provide a way to encode a different conflict-resolution preference into timestamp strings.

Note that the `Z` offset exception is needed because, as noted in [this mailing list post](https://mailarchive.ietf.org/arch/msg/sedate/ASuUtP1euUmyaetyv7do6iCfAjo/), many applications (and libraries like java.time) use `Z` to mean "I don't know the local offset".

<details><summary>ORIGINAL CONTENT (LONG)</summary>

Here's how Temporal handles conflicts like this in our current API design:
1. A "conflict" means that the date and time shown in the timestamp is not valid for the time zone in brackets, according to the TZDB rules that the parsing program is using.
2. If there's a conflict, by default an exception is thrown when parsing.
3. The offset `Z` will never cause a conflict, because Temporal interprets `Z` as a "null time zone" that is not asserting anything about the local date or local time in a real place on earth. Therefore, the bracketed time zone will take precedence if a `Z` offset is used.
4. Callers can optionally override the behaviors above by calling the parsing function using an optional parameter that controls parsing behavior: `offset: 'use'` will make the offset win, `offset: 'ignore'` will make the bracketed extension win, and `offset: 'reject'` is the default behavior. 

We'd prefer the standardized behavior to be compatible with the current Temporal implementation described above. 

But if we must make a change, then we'd be OK to change the default behavior from "throw an exception in case of conflict" to "non-Z offsets always win".  We think that "throw on conflict" is the best default behavior because it helps the developer detect conflicts which would otherwise go unnoticed by the 99% of developers who'll never anticipate possible conflicts. But we also acknowledge valid arguments in favor of an "offset wins by default" behavior.

We WOULD NOT be OK with a behavior that always rejects Z offsets with bracketed time zones, because that would prevent creating strings where the original local date/time is unknown. This "don't know the offset" limitation is very common for timestamps stored in a relational database and other systems that only store a "time since epoch" value without an offset. In those cases, there's no clear alternative to using a Z offset in the string.

We WOULD NOT be OK with a change that prevented Temporal from providing callers with an option (see (4) above) to override the default conflict-resolution behavior. The ability for callers to have an opt-in way to decide conflict resolution behavior is important because, as discussed above in the Brazil example, in rare cases valid strings will later become conflicting. In many cases, it's not practical for these previously-stored strings to be updated. (For example, they may be stored in a database owned by someone else.) So programmers need to have a way to deal with those kinds of strings if they receive them.

</details>

**Comment by justingrant** [comment]
@ryzokuken and I discussed this issue tonight in context of recent discussions on the WG, and I just updated the OP to simplify and and clarify Temporal's requests to align with the latest WG discussions.

Apologies for late-breaking updates, but hopefully it should simplify the discussion in the real-time meeting.

**Comment by cabo** [comment]
While most of this is covered by the new Section 2, we could discuss what is remaining under #25.
