### ISSUE TITLE
We seem to ignore the lessons learned and documented in RFC 6648 (“x-dash”).

### ISSUE THREAD

**Issue by cabo** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#2]

**Comment by ryzokuken** [comment]
Also CCing other stakeholders directly for greater visibility.

**Comment by sffc** [comment]
CC @sffc @macchiati to comment about namespacing and extensions.

**Comment by cabo** [comment]
-02 has a cleaned up naming and name spacing system.
https://www.ietf.org/archive/id/draft-ietf-sedate-datetime-extended-02.html#section-2.2-4.2 now defines an "x-" namespace and restricts usage of that to actual experiments.
Is that what we want to do?
Is that all we need to do?
Discuss.
