### ISSUE TITLE
How to resolve duplicate calendar annotations?  (Error handling.)

### ISSUE THREAD

**Issue by sffc** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#25]
BCP-47 takes the first when there is a duplicate:

```javascript
> new Intl.Locale("en-u-ca-buddhist-ca-hebrew").calendar
// buddhist
```

**Comment by cabo** [comment]
https://www.ietf.org/archive/id/draft-ietf-sedate-datetime-extended-05.html#section-2.1-5
addresses this -- the comment in yellow shows we haven't quite converged yet.

Can you cite chapter and verse for the BCP-47 behavior you are describing?

**Comment by ptomato** [comment]
Additionally, if we do take the first - should the flag matter in `[u-ca=cal1][!u-ca=cal2]`?

**Comment by cabo** [comment]
So we should pick up the remaining part of issue #17 and also should resolve the comment in yellow cited above.

**Comment by justingrant** [comment]
@cabo - I assume that this issue must be resolved before this RFC can be published?  

> Can you cite chapter and verse for the BCP-47 behavior you are describing?

@sffc can you help @cabo with this?

**Comment by sffc** [comment]
I browsed UTS 35 and I can't actually find if the specification states this behavior, or if it is only an artifact of the implementation. @zbraniecki @macchiati ?

**Comment by brong** [comment]
Agreed at IETF116 that we choose first item if there are duplicates.

If multiple non-critical, first takes precedence.  If any critical and multiple, it's invalid.

E.g.

```
u-ca=chinese,u-ca=japanese -> chinese
!u-ca=chinese,u-ca=japanese -> invalid
u-ca=chinese,!u-ca=japanese -> invalid
```
