### ISSUE TITLE
Possible clarifications around IANA TZs

### ISSUE THREAD

**Issue by ucarion** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#31]
Forgive the three-in-one issue. Happy to re-file issues separately if they're worth triaging independently.

---

The definition of IANA Time Zone reads:

> Note that the rules defined for a named IANA time zone can change over time. The use of a named IANA time zone implies that the intent is for the rules that are current at the time of interpretation to apply, i.e., the additional information conveyed by using that time zone name is to change with the changed rules as recorded in the IANA time zone database.

The document doesn't clarify what "current" means. In practice, I suspect real software will always apply whatever they can find in `/usr/share/zoneinfo`, so I doubt anything else could be prescribed here. But "current" suggests that compliant software must always have the latest tz db at hand. Should this be spelled out a bit more?

---

Also, even though it's heavily implied throughout, I'm not sure I see language in the document explicitly stating that the `time-zone` ABNF rule, elsewhere called the "time zone suffix", must be an IANA Time Zone. Might this make sense to say explicitly? It's possible I'm not reading carefully enough.

---

Finally, I'm not sure what an application is supposed to do if it encounters an IANA Time Zone that it does not know about. This is similar to the case of inconsistency in Section 3.4 (maybe the application is running an old tz db, and the latest release includes a new timezone). Might it be worth clarifying that this is a possibility? 

For what it's worth, I think the current, broad language in Section 3.4 about acting on inconsistencies is sufficient, supposing we consider this to be just another kind of inconsistency. Users may be surprised that `2022-07-08T00:14:07+00:00[foobar]` is merely "inconsistent" and not "utterly invalid", but I don't see what alternatives would exist.

**Comment by justingrant** [comment]
Hi @ucarion - Thanks for the suggestions. I'm working on an editorial PR in #35 and will address your feedback there.  Let me know if you see problems with the changes proposed below.


> The document doesn't clarify what "current" means. In practice, I suspect real software will always apply whatever they can find in `/usr/share/zoneinfo`, so I doubt anything else could be prescribed here. But "current" suggests that compliant software must always have the latest tz db at hand. Should this be spelled out a bit more?

I updated to this text: 

> Rules defined for a named IANA time zone can change over
> time.
> Applications SHOULD use the most recent TZDB version to
> interpret the time zone suffix in IXDTF strings.

----------------

> Also, even though it's heavily implied throughout, I'm not sure I see language in the document explicitly stating that the `time-zone` ABNF rule, elsewhere called the "time zone suffix", must be an IANA Time Zone. Might this make sense to say explicitly? It's possible I'm not reading carefully enough.

I added this note under the ABNF: 

> Also note that `time-zone-name` MUST be the name of an IANA Time Zone.

----------

> I'm not sure what an application is supposed to do if it encounters an IANA Time Zone that it does not know about. This is similar to the case of inconsistency in Section 3.4 (maybe the application is running an old tz db, and the latest release includes a new timezone). Might it be worth clarifying that this is a possibility?

Here's some current text related to this issue. Do you think this is sufficient?

> Without further indication, suffix tags are also *elective*: a recipient
> MAY ignore any or all suffix tags included in an IXDTF string.
> Reasons might include that the recipient does not implement (or know
> about) the specific suffix key, or that it recognizes the key but cannot
> act on its value.
>

**Comment by cabo** [comment]
> The document doesn't clarify what "current" means.

No, but it uses this word in a phrase that is about the intent of the generator -- so "current" is a statement from the view of the generator.  There is no onus placed on anyone by this statement of intent; there is definitely nothing in this sentence that implies that "compliant software must always have the latest tz db".
