### ISSUE TITLE
Clarify that legacy Etc/GMT* are not recommended by this document

### ISSUE THREAD

**Issue by cabo** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#33]
Martin Dürst:

> Many thanks for the explanations. Summarized, they say "Don’t use Etc/GMT*". That's well and good, but the document doesn't say so. It says:

> >>>>
> Special IANA time zones such as Etc/GMT+10 can be used to represent timestamps outside country boundaries, e.g. a buoy in the middle of the Pacific Ocean (note that the Etc/GMT+10 time zone has a constant UTC Offset of -10:00 [sic!]).
> >>>>

> So I repeat my plea to clarify this so that even a reader of the document without any access to experts such as those on this mailing list will understand things correctly without getting confused first.

**Comment by ediosyncratic** [comment]
It might be better to rework the (note ... [sic]!) into a clear reminder that the sign is off, e.g.

(note that these legacy zone names use a reverse convention for the offset, so Etc/GMT+10 has a constant UTC Offset of -10:00).

**Comment by justingrant** [comment]
To avoid confusion, in #35 I propose simply removing mention of the `Etc/GMT*` zones completely.
