### ISSUE TITLE
Should we enshrine the 14-character limit to TZ name parts?

### ISSUE THREAD

**Issue by cabo** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#46]
> while the 14-character limit is indeed
documented in the IANA DB's rules for names, those rules do include a
"grandfather" clause for names in use before the rules were formulated.
I haven't stopped to check whether that actually affects the grammar,
but it might be constructive to look through the IANA DB for any names
that violate the rules.

> I have, also, seen some platforms violating the 14-chracter limit in
some of their idiosyncratic names for zones, notably Android has a
Canada/East-Saskatchewan zone, with a 17-character component.

Archived-At: <https://mailarchive.ietf.org/arch/msg/sedate/PPYbgmNUe3r3rEPKcLCFbt3cczM>

It seems wrong to cast this in concrete when we know the rule is utterly outdated (when did the last system with the 14-character limit die) and also actively ignored.

**Comment by ediosyncratic** [comment]
Plenty of systems with the 14-character limit ship routinely.  On all non-Android platforms, Qt's QTimeZone imposes the 14-character limit, for example.  (I am the author of the quoted snippet from e-mail, above, and maintainer of QTimeZone.)

However, it's not necessary for the sedate spec to hard-code that rule: software systems reading a zone name will have a further step of looking up that name in the IANA DB and they won't get a match if it's not real.  So sedate has the option of using a slacker spec, that the subsequent lookup will effectively convert to the 14-character rule aside from any grandfatered-in old names that might violate it.  Note that the Android example I quoted above is not a name used by the IANA DB; I'm not sure where Android gets it (might be ICU), but it's not IANA.

**Comment by cabo** [comment]
Sorry for being ambiguous: when I said

> when did the last system with the 14-character limit die

I meant the last system that really still has a 14-character limit in the file system.

I think I agree with your points; it appears we should remove the 13 (and the redundant parentheses) from

``` 
time-zone-part    = time-zone-initial *13(time-zone-char)
```
