### ISSUE TITLE
ISO8601 reference may need to be split to multiple editions

### ISSUE THREAD

**Issue by cabo** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#48]
`-00:00` became unambiguously outlawed only in the 2000 edition, we are referencing ISO8601:1988 throughout.

(We may also use the opportunity to point to an openly available rendition of ISO 8601:1988,
https://nvlpubs.nist.gov/nistpubs/Legacy/FIPS/fipspub4-1-1991.pdf
)

**Comment by ryzokuken** [comment]
@cabo great point! Thanks for the link, I was not sure this was widely available.

**Comment by cabo** [comment]
Archived-At: <https://mailarchive.ietf.org/arch/msg/last-call/Ctib-yt0hqEn9_RA-pkPyPrNKpU>

> > (Note that referencing a newer version would also erect a
paywall that would hamper review; please remind yourself of
the discussion we had around Archived-At:
<https://mailarchive.ietf.org/arch/msg/sedate/bvn8eA-DFWB3U1oF
hkVI-QEih0Q> ).

> Per that discussion (and as now mentioned at that Github link),
if a link to the FIPS publication were added to the one to the
ISO page, with a comment like "still available at", it would
considerably mitigate my concern.
