### ISSUE TITLE
Support Floating time?

### ISSUE THREAD

**Issue by cabo** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#7]
i.e., time without a specified timezone.

**Comment by cabo** [comment]
John Klensin: ""ingenious" gives me the creeps.  If we need to do something, let's make it explicit and avoid heuristics or cleverness to which people will need to adapt."

**Comment by ryzokuken** [comment]
@cabo this is out of scope after all, right? Perhaps we can close this now.
