### ISSUE TITLE
We need to name the baby

### ISSUE THREAD

**Issue by cabo** [ietf-wg-sedate/draft-ietf-sedate-datetime-extended#9]
We need a name that people will use until they can say RFC9999 timestamps (and maybe even when they can).

**Comment by justingrant** [comment]
"Extended Timestamps" or "Extended Internet Timestamps" ?

**Comment by cabo** [comment]
RFC 3339 says "Internet Date/Time Format".

That is what sedate says at the moment as well, but that can't stay the same.

So I'm considering moving to:

* Internet Date/Time Format Extended

The alternative ....

* Extended Internet Date/Time Format

sounds like a date/time format for the Extended Internet (EI is actually in use as "Extensible Internet", which this shouldn't be confused with).

I'd rather call it Fritz, but I haven't found a way to retronym this...
